FROM quay.io/pypa/manylinux2014_x86_64:latest
RUN yum -y install wget
RUN cd tmp && wget https://ftp.gnu.org/gnu/gcc/gcc-10.1.0/gcc-10.1.0.tar.gz && tar xzf gcc-10.1.0.tar.gz
RUN cd /tmp/gcc-10.1.0 && ./contrib/download_prerequisites
RUN mkdir /tmp/gcc-10.1.0/build && cd /tmp/gcc-10.1.0/build && ../configure --enable-languages=c,c++ --disable-multilib && make -j8 && make install
RUN rm -rf /tmp/gcc-10.1.0 && rm /tmp/gcc-10.1.0.tar.gz
